# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b21b124fbeba9f1b613cc2212155b0ea86de83515ec99c84e61da1a7a03a42b61a4ae9e6c4221e0661dd9ef961140d6a6418c76b4fb3ac442e0e96e7b8f9616c

test:
  secret_key_base: e73dd9fc111f399543521f453b277cd796ede5633afd540fe322cbe5d2878e59075da30f94566c652970e6aec1da02b55c0d19bd82382d4be9ff83a0c854a287

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
